PassionProject/Models/User.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace PassionProject.Models
{
    public class User
    {
        [Key]
        public string UserId {  get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }

        public ICollection<Application> Applications { get; set; }
        


    }
    public class UserDto
    {
        public string UserId { get; set; }
        public string UserName { get; set; }
        public string UserEmail { get; set; }
        public string UserPassword { get; set; }


    }
}

PassionProject/Controllers/PetController.cs
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web.Mvc;
using PassionProject.Migrations;
using PassionProject.Models;

namespace PassionProject.Controllers
{
    public class PetController : Controller
    {
        private readonly string apiBaseUrl = "https://localhost:44377/api/petdata/";

        public ActionResult List()
        {
            using (HttpClient client = new HttpClient())
            {
                string url = apiBaseUrl + "listpets";
                HttpResponseMessage response = client.GetAsync(url).Result;

                if (response.IsSuccessStatusCode)
                {
                    var pets = response.Content.ReadAsAsync<List<PetDto>>().Result;
                    return View("PetList", pets);
                }
                else
                {
                    ViewBag.ErrorMessage = "Error retrieving pets.";
                    return View("Error");
                }
            }
        }


        public ActionResult Apply(int petId)
        {
            using (ApplicationDbContext db = new ApplicationDbContext())
            {
                var petDetails = db.Pets
                    .Where(p => p.PetId == petId)
                    .Select(p => new PetDto
                    {
                        PetId = p.PetId,
                        PetName = p.PetName,
                       
                    })
                    .FirstOrDefault();

                if (petDetails != null)
                {
                    ViewBag.PetDetails = petDetails;

                   
                    return RedirectToAction("ApplicationList", "Application", new { petId });
                }
            }

            ViewBag.ErrorMessage = "Error retrieving pet details.";
            return View("Error");
        }

       
    }
}

PassionProject/Controllers/UserController.cs
using PassionProject.Models;
using System.Collections.Generic;
using System.Net.Http;
using System.Web.Mvc;

namespace PassionProject.Controllers
{
    public class UserController : Controller
    {
        private readonly string apiBaseUrl = "https://localhost:44377/api/userdata/";

        public ActionResult List()
        {
            using (HttpClient client = new HttpClient())
            {
                string url = apiBaseUrl + "users";
                HttpResponseMessage response = client.GetAsync(url).Result;

                if (response.IsSuccessStatusCode)
                {
                    var users = response.Content.ReadAsAsync<List<UserDto>>().Result;
                    return View("List", users);
                }
                else
                {
                    
                    return RedirectToAction("List");
                }
            }
        }

        public ActionResult New()
        {
            return View("New");
        }

        [HttpPost]
        public ActionResult Create(UserDto newUser)
        {
            if (ModelState.IsValid)
            {
                using (HttpClient client = new HttpClient())
                {
                    string url = apiBaseUrl + "create";
                    HttpResponseMessage response = client.PostAsJsonAsync(url, newUser).Result;

                    if (response.IsSuccessStatusCode)
                    {
                        return RedirectToAction("List");
                    }
                    else
                    {
                        
                        ModelState.AddModelError(string.Empty, "Error creating user");
                    }
                }
            }

            return View("New", newUser);
        }
    }
}

PassionProject/Views/User/List.cshtml
@model IEnumerable<PassionProject.Models.UserDto>

@{
    ViewBag.Title = "List";
}

<h2>List</h2>

<div class="row">
    @foreach (var user in Model)
    {
        <div class="col-md-4 mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">User ID: @user.UserId</h5>
                    <p class="card-text">User Name: @user.UserName</p>
                    <p class="card-text">User Email: @user.UserEmail</p>
                    <p class="card-text">User Password: @user.UserPassword</p>

                    <div class="btn-group" role="group" aria-label="User Actions">
                        <a href="#" class="btn btn-primary" onclick="openUpdateModal('@user.UserId')">Update</a>
                        <a href="#" class="btn btn-danger" onclick="confirmDelete('@user.UserId')">Delete</a>
                        <a href="@Url.Action("List", "Pet")" class="btn btn-success">Explore Pets</a>
                    </div>
                </div>
            </div>
        </div>
    }
</div>

<div class="text-center mt-4">
    <a href="@Url.Action("New", "User")" class="btn btn-primary">Create A New User</a>
</div>

<!-- Modal for Update -->
<div class="modal fade" id="updateModal" tabindex="-1" role="dialog" aria-labelledby="updateModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="updateModalLabel">Update User</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                
            </div>
        </div>
    </div>
</div>

@section scripts {
    <script>
        function confirmDelete(userId) {
            if (confirm("Are you sure you want to delete this user?")) {
                var xhr = new XMLHttpRequest();
                xhr.open("DELETE", "/api/UserData/delete/" + userId, true);

                xhr.onload = function () {
                    if (xhr.status == 200) {
                        location.reload(); // Reload the page after deletion
                    } else {
                        alert("Error deleting user");
                    }
                };

                xhr.send();
            }
        }

        function openUpdateModal(userId) {
            var modal = document.getElementById("updateModal");
            var modalBody = modal.querySelector(".modal-body");

            // Fetch the user data to populate the update form
            var xhr = new XMLHttpRequest();
            xhr.open("GET", "/api/UserData/user/" + userId, true);

            xhr.onload = function () {
                if (xhr.status == 200) {
                    var userData = JSON.parse(xhr.responseText);

                    
                    var updateForm = document.createElement("form");
                    updateForm.innerHTML = `
                            <div class="form-group">
                                <label for="updateUserName">User Name</label>
                                <input type="text" class="form-control" id="updateUserName" value="${userData.UserName}" required>
                            </div>
                            <div class="form-group">
                                <label for="updateUserEmail">User Email</label>
                                <input type="email" class="form-control" id="updateUserEmail" value="${userData.UserEmail}" required>
                            </div>
                            <div class="form-group">
                                <label for="updateUserPassword">User Password</label>
                                <input type="password" class="form-control" id="updateUserPassword" value="${userData.UserPassword}" required>
                            </div>
                            <button type="button" class="btn btn-primary" onclick="submitUpdate('${userId}')">Update</button>
                        `;

                    modalBody.innerHTML = "";
                    modalBody.appendChild(updateForm);

                    // Show the modal
                    $(modal).modal("show");
                } else {
                    alert("Error fetching user data");
                }
            };

            xhr.send();
        }

        function submitUpdate(userId) {
            var updateUserName = document.getElementById("updateUserName").value;
            var updateUserEmail = document.getElementById("updateUserEmail").value;
            var updateUserPassword = document.getElementById("updateUserPassword").value;

            var updatedUser = {
                UserName: updateUserName,
                UserEmail: updateUserEmail,
                UserPassword: updateUserPassword
            };

            var xhr = new XMLHttpRequest();
            xhr.open("PUT", "/api/UserData/update/" + userId, true);
            xhr.setRequestHeader("Content-Type", "application/json");

            xhr.onload = function () {
                if (xhr.status == 200) {
                    location.reload(); 
                } else {
                    alert("Error updating user");
                }
            };

            xhr.send(JSON.stringify(updatedUser));
        }
    </script>
}

PassionProject/Views/User/New.cshtml
@model PassionProject.Models.UserDto

@{
    ViewBag.Title = "Create User";
}

<h2>Create User</h2>

@using (Html.BeginForm("Create", "User", FormMethod.Post))
{
    <div class="form-group">
        <label for="UserId">User ID:</label>
        @Html.TextBoxFor(model => model.UserId, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label for="UserName">User Name:</label>
        @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label for="UserEmail">User Email:</label>
        @Html.TextBoxFor(model => model.UserEmail, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label for="UserPassword">User Password:</label>
        @Html.PasswordFor(model => model.UserPassword, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Create User</button>
}

PassionProject/Views/User/Update.cshtml
@model PassionProject.Models.UserDto

@{
    ViewBag.Title = "Update User";
}

<h2>Update User</h2>

@using (Html.BeginForm("SaveUpdate", "User", FormMethod.Post))
{
    @Html.HiddenFor(model => model.UserId)

    <div class="form-group">
        <label for="UserName">User Name:</label>
        @Html.TextBoxFor(model => model.UserName, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label for="UserEmail">User Email:</label>
        @Html.TextBoxFor(model => model.UserEmail, new { @class = "form-control" })
    </div>

    <div class="form-group">
        <label for="UserPassword">User Password:</label>
        @Html.PasswordFor(model => model.UserPassword, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-primary">Save Changes</button>
}